<div class="row" style="margin-top: 20px;">
    <div class="col-md-8 col-md-offset-2">
        <div class="page-header">
            <h2>Legújabb 10 tétel</h2>
        </div>
        <?=$this->latestNItem()?>
    </div>
</div>

<script>
$.get('/news', function(result){
    $.each(result.feeds, function(index, feed){
        var feedDiv = $("<div class='col-md-4 feed-col'></div>"),
            first = true;
        
        feedDiv.append("<div class='title'>"+index+"</div>");
        
        $.each(feed.posts, function(postIndex, post){
            var postDiv = $("<article class='post'></article>");
            
            if (first) {
                postDiv.addClass("visible f");
                first = false;
            }
            
            postDiv.append("<strong><a href='"+post.link+"'>"+post.title+"</a></strong>");
            postDiv.append("<div class='desc'>"+post.desc+"<br><em>"+ post.date +"</em></div>");
            feedDiv.append(postDiv);
        });
        
        $("#news-target").append(feedDiv);
        
        $("#more-news").click(function(){
            $(this).toggleClass("all");
            
            if ($(this).hasClass("all")) {
                $("#news-target").find(".post").not(".visible").addClass("visible");
                $(this).removeClass("glyphicon-chevron-down")
                        .addClass("glyphicon-chevron-up");
            } else {
                $("#news-target").find(".post").not(".f").removeClass("visible");
                $(this).removeClass("glyphicon-chevron-up")
                        .addClass("glyphicon-chevron-down");
            }
        });
        
        $("#hide-news").click(function(){
           $(".head-news").fadeOut(); 
        });
        
        $(".head-news").fadeIn();
    });
},'json');
</script>