<style>
    .hidden {
        display: none;
    }
</style>
<h1>Tétel szerkesztés</h1>
<div class="item-edit-form">
    <?php
    $form = $this->form;
    $form->setAttribute("action", $this->url("items",array(
        array('action' => 'edit')
    ),false,true));
    $form->setAttribute("class", "form-horizontal");
    $form->prepare();

    $item = $form->get('item');
    ?>
    
    <?=$this->form()->openTag($form);?>
    <?=$this->formHidden($item->get('id'))?>
    <?=$this->formHidden($form->get('security'))?>
    
    <?php 
    $title = $item->get('title');
    $title->setLabelAttributes(array('class' => 'control-label'));
    ?>
    <div class="control-group">
        <?=$this->formLabel($title)?>
        <div class="controls">
            <?=$this->formInput($title)?>
            <?=$this->formElementErrors()
                ->setMessageOpenFormat("<span class='help-inline'>")
                ->setMessageSeparatorString("</span><span class='help-inline'>")
                ->setMessageCloseString("</span>")
                ->render($title)
            ?>
        </div>
    </div>
    
    <?php
    $category = $item->get('category');
    $category->setLabelAttributes(array('class' => 'control-label'));
    ?>
    <div class="control-group">
        <?=$this->formLabel($category)?>
        <div class="controls">
            <?=$this->formSelect($category)?>
        </div>
    </div>
    
    <?php
    $useCustom = $item->get('set-custom-category');
    $useCustom->setLabelAttributes(array('class' => 'checkbox'));
    ?>
    <div class="control-group">
        <div class="controls">
            <?=$this->formLabel($useCustom, $this->formCheckbox($useCustom), 'append')?>
        </div>
    </div>
    
    <?php
    $custom = $item->get('custom-category');
    $custom->setLabelAttributes(array('class' => 'control-label'));
    ?>
    <div class="control-group hidden" id="custom-category">
        <?=$this->formLabel($custom);?>
        <div class="controls">
            <?=$this->formInput($custom)?>
        </div>
    </div>
    <script>
    $("#set-custom-category").click(function(){
        $("#custom-category").toggle("hidden");
    });
    </script>
    
    <?php
    $num = $item->get('itemNum');
    $num->setLabelAttributes(array('class' => 'control-label'));
    ?>
    <div class="control-group">
        <?=$this->formLabel($num)?>
        <div class="controls">
            <?=$this->formNumber($num)?>
        </div>
    </div>
    
    <div class="control-group">
        <div class="controls">
            <?=$this->formSubmit($form->get('submit'));?>
        </div>
    </div>

    <?=$this->form()->closeTag($form);?>
</div>