<div class="row">
    <div class="col-md-12">
        <div class="panel panel-danger">
            <div class="panel-heading">
                Hiba történt!
            </div>
            <div class="panel-body">
                <p>Valószínűleg végzetes hiba történt! Talán próbáld meg később</p>
            </div>
            <div class="panel-footer">
                A kellemetlenségért elnézést kérek.
            </div>
        </div>
    </div>
</div>