<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Class Page</title>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/jquery.form.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.upload.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="navbar-inner">
                <div class="container">
                    <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="brand" href="<?php echo $this->url('home') ?>">&nbsp; Class Oldal</a>
                    <div class="collapse nav-collapse">
                        <p class="navbar-text pull-right">
                            <?php echo $this->userBar(); ?> | 
                            <a href="<?php echo $this->url('logout'); ?>">Kilépés</a>
                        </p>
                        <ul class="nav">
                            <li <?php if ($this->isActiveRoute('home')): ?> class="active" <?php endif; ?>><a href="<?php echo $this->url('home') ?>">Főlap</a></li>
                            <li 
                                <?php if ($this->isActiveRoute('items')): ?> 
                                    class="active dropdown" 
                                <?php else: ?> 
                                    class="dropdown"
                                <?php endif; ?>>
                                
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    Tételek
                                    <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?php echo $this->url('items', array('action' => 'upload')) ?>">Feltöltés</a></li>
                                    <li><a href="<?php echo $this->url('items') ?>">Letöltések</a></li>
                                    <li class="nav-header">Kategóriák</li>
                                    <?php foreach ($this->categoryMenu() as $menu): ?>
                                        <?=$menu?>
                                    <?php endforeach; ?>
                                </ul>
                            </li>
                            <li <?php if ($this->isActiveRoute('profile')): ?> class="active" <?php endif ?>><a href="<?php echo $this->url('profile'); ?>">Profil</a></li>
                            <li></li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2013 - <?php echo date('Y') ?> by Metál Ádám, 
                    <a href="https://twitter.com/metalica155" target="_blank">Twitter</a> | 
                    <a href="http://geekmee.wordpress.com/" target="_blank">Wordpress</a></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
