<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('class', 'form-horizontal');
$form->setAttribute('role','form');
?>

<div class="row">
    <div class="col-md-offset-2 col-md-8">
    <?=$this->form()->openTag($form);?>
    
        <?=$this->formHidden($form->get('security'));?>
        
        <div class="form-group">
            <?=$this->formLabel($form->get('reg-code'))?>
            <div class="col-sm-9">
                <?=$this->formText($form->get('reg-code'))?>
                <?=$this->formElementErrors($form->get('reg-code'))?>
            </div>
        </div>
        
        <div class="form-group">
            <?=$this->formLabel($form->get('nick'));?>
            <div class="col-sm-9">
                <?=$this->formText($form->get('nick'));?>
                <?=$this->formElementErrors($form->get('nick'));?>
            </div>
        </div>
    
        <div class="form-group">
            <?=$this->formLabel($form->get('email'));?>
            <div class="col-sm-9">
                <?=$this->formEmail($form->get('email'));?>
                <?=$this->formElementErrors($form->get('email'));?>
            </div>
        </div>
    
        <div class="form-group">
            <?=$this->formLabel($form->get('confirm_email'));?>
            <div class="col-sm-9">
                <?=$this->formEmail($form->get('confirm_email'));?>
                <?=$this->formElementErrors($form->get('confirm_email'));?>
            </div>
        </div>
    
        <div class="form-group">
            <?=$this->formLabel($form->get('pass'));?>
            <div class="col-sm-9">
                <?=$this->formPassword($form->get('pass'));?>
                <?=$this->formElementErrors($form->get('pass'));?>
            </div>
        </div>
    
        <div class="form-group">
            <?=$this->formLabel($form->get('confirm_pass'));?>
            <div class="col-sm-9">
                <?=$this->formPassword($form->get('confirm_pass'));?>
                <?=$this->formElementErrors($form->get('confirm_pass'));?>
            </div>
        </div>
        
        <div class="form-group">
            <label class="col-sm-3">Bizonyítsd emberséged!</label>
            <div class="col-sm-9">
                <?=$this->formElement($form->get('captcha'))?>
                <?=$this->formElementErrors($form->get('captcha'))?>
            </div>
        </div>
    
        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-9">
                <?=$this->formSubmit($form->get('submit'));?>
            </div>
        </div>
    
    <?=$this->form()->closeTag($form);?>
    </div>
</div>