<div class="row">
    <div class="col-md-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <?=$this->category->getName()?> - Tételek
            </div>
            <div class="panel-body">
                <div class="list-group">
                    <?php foreach ($this->items as $item): ?>
                        <a href="#" class="list-group-item">
                          <h4 class="list-group-item-heading"><?=$item->getTitle()?></h4>
                          <p class="list-group-item-text">
                              <?php $uploader = $item->getUploader(); ?>
                              Feltöltő nickneve: <?=$uploader->getNick();?><br>
                              Tétel Leírás: <br>
                              <?=$item->getDesc()?>
                          </p>
                        </a>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
</div>