<div class="row">
    <div class="col-md-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <?=$this->category->getName()?> - Tételek
            </div>
            <div class="panel-body">
                <table class="table table-condensed table-striped">
                    <thead>
                        <tr>
                            <th>Tétel neve</th>
                            <th>Letöltés</th>
                            <th>Adatlap</th>
                            <th>Feltöltve</th>
                            <th>Feltöltő</th>
                            <th>Leírás</th>
                        </tr>
                    </thead>
                    <?php foreach ($this->items as $item): ?>
                    <tr>
                        <?php $itemDownloadLink = $this->url('item',array(
                            'action' => 'download',
                            'id' => $item->getId()
                            )); ?>
                        
                        <?php $itemDataSheetLink = $this->url('item',array(
                            'action' => 'view',
                            'id' => $item->getId()
                        )); ?>
                        
                        <th><a href="<?=$itemDownloadLink?>"><?=$item->getTitle()?></a></th>
                        <td>
                            <a href="<?=$itemDownloadLink?>">
                                <span class="glyphicon glyphicon-download-alt"></span>
                            </a>
                        </td>
                        <td>
                            <a href="<?=$itemDataSheetLink?>">
                                <span class="glyphicon glyphicon-folder-open"></span>
                            </a>
                        </td>
                        <td><?=$item->getCreated()->format('Y-m-d')?></td>
                        <td><?=$item->getUploader()->getNick()?></td>
                        <td><?=$item->getDesc()?></td>
                    </tr>
                    <?php endforeach; ?>
                </table>
            </div>
            <div class="panel-footer">
                <?php $downloadLink = $this->url('category',array(
                    'action' => 'download',
                    'id' => $this->category->getId()
                )); ?>
                
                <a href="<?=$downloadLink?>">Összes letöltése</a>
            </div>
        </div>
    </div>
</div>