<div class="row">
    <div class="col-md-12">
        <div class="panel panel-primary">
            <div class="panel-heading">Új meghívó küldése</div>
            <div class="panel-body">
                <?php 
                $form = $this->form; 
                $form->prepare();
                $form->setAttribute('action',$this->url('invitation',array(
                    'action' => 'create-process'
                )));
                $form->setAttribute('method','post');
                $form->setAttribute('role','form');
                ?>
                
                <?=$this->form()->openTag($form)?>
                <div class="form-group">
                    <?php $email = $form->get('email');
                          $email->setAttribute('class','form-control');?>
                    
                    <?=$this->formLabel($email)?>
                    <?=$this->formElement($email)?>
                    <?=$this->formElementErrors($email)?>
                </div>
                
                <div class="form-group">
                    <?=$this->formLabel($form->get('captcha'))?>
                    <?=$this->formElement($form->get('captcha'))?>
                    <?=$this->formElementErrors($form->get('captcha'))?>
                </div>
                
                <?=$this->formElement($form->get('csrf'))?>
                
                <?php $submit = $form->get('send');
                      $submit->setAttribute('class','btn btn-default'); ?>
                
                <?=$this->formElement($submit)?>
                
                <?=$this->form()->closeTag($form)?>
            </div>
        </div>
    </div>
</div>